class Config:
    INITIAL_RANGE = 1
    MAX_RANGE = 2000
    DROP_PROB_SENDER = 0
    DROP_PROB_RECEIVER = 0
    DEAD_RECKONING_ANGLE = 0
    ACCELERATION = 6
    DECELERATION = 6
    MAX_SPEED = 6
    DISPLAY_CELL_SIZE = 0.05
    BUSY_WAITING = False
    SAMPLE_SIZE = 0
    DURATION = 600
    READ_FROM_NPY = 0
    K = 3
    SHAPE = 'chess'
    RESULTS_PATH = 'results'
    DEBUG = True
    FILE_NAME_KEYS = ['K']  # list of properties that should be used in the name of results file names
    DIR_KEYS = ['H']  # list of properties that should be used in the name of results directory
    SERVER_TIMEOUT = 120
    PROCESS_JOIN_TIMEOUT = 120
    NUM_DISPATCHERS = 1
    MULTICAST = True
    TIMELINE_LOG = False
    OPT_SORT = True
    TEST_ENABLED = True
    NUMBER_OF_FLSS = 12
    R = 10  # ratio of r2 to r1
    H = "canf"  # valid values for heuristic: simpler, canf, vns, rs
    VNS_TIMEOUT = 0.1
    EXPANSION_TIMEOUT = 0.05
    ETA = K - 1  # initial eta only effective for h:1 and h:rs
    ETA_STR = "k-1"
